### ISSUE TITLE
Currently not Working (Request Failed Message)

### ISSUE THREAD

**Issue by jheindo1** [Mintonne/Publisher-Extension-for-Unity3D#38]
Currently, whenever I try to access sales, downloads or revenue tab it says "Request failed". This happens for a little less than a week. (somewhere around 15.10.2019).
Note: Reviews tab is still working.

**Comment by Mintonne** [comment]
Info - https://blog.chromium.org/2019/10/recent-site-isolation-improvements.html

Cookies are now no longer getting sent with requests made from the extension. This change completely breaks how the extension works.

I have unpublished the extension for now.

**Comment by jheindo1** [comment]
It worked again today. Is it fixed?

**Comment by Mintonne** [comment]
It seems one of the updates fixed this. Should work again now.
