### ISSUE TITLE
Total Payout calculated wrong number

### ISSUE THREAD

**Issue by jheindo1** [Mintonne/Publisher-Extension-for-Unity3D#5]
From my understanding, the total payout should equal "Net revenue" minus "Current Balance".
Now my Net Revenue shows the correct accumulated Revenue, but the total payout is much smaller. The current balance in 0$, which is correct.
If it's my false understanding of what the values mean, please give me a hint. Otherwise, I think this is a bug.
If the actual numbers are needed please contact me directly, because I don't want to share them publically.

**Comment by Mintonne** [comment]
> From my understanding, the total payout should equal "Net revenue" minus "Current Balance".

Ideally, that is how it should work.

Kindly send me a screenshot of your revenue page from the [Publisher Dashboard ](https://publisher.assetstore.unity3d.com/revenue.html) (Crop out the **Debit**, **Credit** & **Balance** sections).

Email - mintonne(at)gmail.com

**How to capture a full page screenshot**

* **Chrome** - [Blipshot ](https://chrome.google.com/webstore/detail/blipshot-one-click-full-p/mdaboflcmhejfihjcbmdiebgfchigjcf) extension (Opensource)

* **Firefox** - CTRL/CMD + SHIFT + S

**Comment by jheindo1** [comment]
An email with a screenshot was sent to the email provided.
